### ISSUE TITLE
Crash when uploading image

### ISSUE THREAD

**Issue by sbleon** [ihoka-me/radiant-tiny-paper-extension#1]
I'm totally new to Radiant, and tiny_paper, so I apologize in advance for my noob-ness here.
I just installed Radiant 0.8.1. I installed paperclipped, will_paginate, and tiny_paper per your instructions. The first thing I tried to do was upload an image into a page. After I selected an image and pressed Upload, I got this error:

NoMethodError in Admin/tiny_paper#images

Showing vendor/extensions/tiny_paper/app/views/admin/tiny_paper/_images_sizes.html.haml where line #6 raised:

undefined method `each' for #Proc:0x244de80
Extracted source (around line #6):

3: %p= asset.title
4: %div
5:   %table#sizes
6:     - @thumbnails.each do |k, v|
7:       %tr
8:         %th= link_to k, asset.asset.url(k)
9:         %td= asset.width(k).to_s + 'px x ' + asset.height(k).to_s + 'px'
Trace of template inclusion: vendor/extensions/tiny_paper/app/views/admin/tiny_paper/_images_images.html.haml, vendor/extensions/tiny_paper/app/views/admin/tiny_paper/images.html.haml

**Comment by sbleon** [comment]
Thanks for the cool plugin. So far Radiant seems like a great system. I wish I was enough of a Rails hacker to figure out the error and suggest a fix, but I'm still learning.

**Comment by iphilgood** [comment]
Haha yeah it's a really nice plugin but i've got the same problem. If I delete all after «- @thumbnails» it renders me the uploaded images. The next problem is I can't chose a picture and insert it in my content.

**Comment by Vince-Cercury** [comment]
Having the same problem here too. Using Radiant 0.8.1.
Any ideas / solution ?

**Comment by iphilgood** [comment]
In Radiant 0.9.0 you have to checkout the branch «0.9.0» of the paperclipped extension. Now it works! Thanks!

**Comment by stegel** [comment]
what about in radiant 0.8.2?

**Comment by cristi** [comment]
pushed a fix in 0.8 branch. Should fix the issue for Radiant 0.8.1 and 0.8.2.

For Radiant 0.9 be sure to checkout branch 0.9.0 of paperclipped. It works for me

**Comment by stegel** [comment]
Thanks, this worked!

**Comment by archercom** [comment]
I get the same error using 0.7.1.  Any chance of a fix for that branch?  I now use 0.9 but this is for one of my older projects.

ActionView::TemplateError (undefined method `each' for #Proc:0x7f8d2b69ac70) on line #5 of vendor/extensions/tiny_paper/app/views/admin/tiny_paper/_images_sizes.html.haml:
2: %p= asset.title
3: %div
4:   %table#tp_sizes
5:     - @thumbnails.each do |k, v|
6:       %tr
7:         %th= link_to k, asset.asset.url(k)
8:         %td= asset.width(k).to_s + 'px x ' + asset.height(k).to_s + 'px'

**Comment by archercom** [comment]
nevermind, I had to make sure the settings extension was raked before paperclipped

**Comment by cristi** [comment]
fixed and closed

**Comment by joepmath** [comment]
In: vendor/extensions/tiny_paper/app/views/admin/tiny_paper/_images_sizes.html.haml

I changed '@thumbnails.each' to '@thumbnails.call.each'. That solves the problem.
We use Radiant-0.9.1.
