### ISSUE TITLE
'Rich Text Editor' can't be default page part

### ISSUE THREAD

**Issue by nelstrom** [ihoka-me/radiant-tiny-paper-extension#2]
I may be missing something, but if I set Radiant::Config['defaults.page.filter'] = 'Rich Text Editor' it doesn't activate as the default filter. I think the problem stems from the spaces in the name of the filter. 

I've also tried using this with the stereotype extension, e.g.:

```
Radiant::Config['stereotype.article.parts'] = body:textile,extended:Rich\ Text\ Editor
```

No luck. Is there a way?

I'm considering replacing 'Rich Text Editor' with 'RichTextEditor'. Or the less user friendly 'tinymce'. Any thoughts?

**Comment by cristi** [comment]
this issue is related to stereotype extension; Fixed in stereotype
