### ISSUE TITLE
Javascript fails on 0.9.0rc2

### ISSUE THREAD

**Issue by simonthesorcerer** [ihoka-me/radiant-tiny-paper-extension#3]
Hi i hope its not just some dumb problem caused by my imcompetence.
But after some issues with 0.8.2 i switched to radiant 0.9.0rc2 after updating and installing the tiny paper extension i have a problem with inserting images into the page:

After opening the image browser i can see the asset thumbnails but if i click on one of them nothing happens the same goes for the sort by title and view mode nothing happens and i only get a error message in my firefox saying that:

document.observe is not a function

uncaught exception: controls.js requires including script.aculo.us' effects.js library

Form is not defined

I hope you can help me with this issue.
Thanks in advance

**Comment by cristi** [comment]
Not a Tiny-Paper issue. Please refer to the mailing list (http://radiantcms.org/mailing-list) for help.
